version: '3.4'
networks:
  internal_network:
    driver: bridge

services:
  redis:
    image: "redis/redis-stack-server:latest"
    command: 
     - redis-server 
     -  --protected-mode no
    ports:
     - "6379:6379"
    expose:
     - "6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data:
